services:
  wheeladvisor:
    image: wheeladvisor:latest
    ports:
      - 80:3000
    volumes:
      - ../src/node/:/app/
      - ../src/website:/app/website
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
