version: '3'
services:
  wheeladvisor:
    image: wheeladvisor:latest
    container_name: wheeladvisor
    ports:
      - 80:3000
    volumes:
      - ../src/node/:/app/
      - ../src/website:/app/website
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
